// <auto-generated />
using CallLogTesting.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallLogTesting.Migrations.FccAmateur
{
    [DbContext(typeof(FccAmateurContext))]
    partial class FccAmateurContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CallLogTesting.Models.Am", b =>
                {
                    b.Property<int>("Fccid")
                        .HasColumnType("int")
                        .HasColumnName("fccid");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("callsign");

                    b.Property<string>("Class")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("class");

                    b.Property<string>("Col4")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("col4");

                    b.Property<string>("Col5")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("col5");

                    b.Property<string>("Col6")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("col6");

                    b.Property<string>("FormerCall")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("former_call");

                    b.Property<string>("FormerClass")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("former_class");

                    b.HasKey("Fccid")
                        .HasName("PK_am_fccid");

                    b.HasIndex(new[] { "Callsign" }, "idx_callsign");

                    b.HasIndex(new[] { "Class" }, "idx_class");

                    b.ToTable("am", "fcc_amateur");
                });

            modelBuilder.Entity("CallLogTesting.Models.En", b =>
                {
                    b.Property<int>("Fccid")
                        .HasColumnType("int")
                        .HasColumnName("fccid");

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address1");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("callsign");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("First")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Last")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last");

                    b.Property<string>("Middle")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("middle");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("zip");

                    b.HasKey("Fccid")
                        .HasName("PK_en_fccid");

                    b.HasIndex(new[] { "Callsign" }, "idx_callsign");

                    b.HasIndex(new[] { "Zip" }, "idx_zip");

                    b.ToTable("en", "fcc_amateur");
                });

            modelBuilder.Entity("CallLogTesting.Models.Hd", b =>
                {
                    b.Property<int>("Fccid")
                        .HasColumnType("int")
                        .HasColumnName("fccid");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("callsign");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("status");

                    b.HasKey("Fccid")
                        .HasName("PK_hd_fccid");

                    b.HasIndex(new[] { "Callsign" }, "idx_callsign");

                    b.HasIndex(new[] { "Status" }, "idx_status");

                    b.ToTable("hd", "fcc_amateur");
                });
#pragma warning restore 612, 618
        }
    }
}
